unit Constnts;

interface

const
  UP    = 0;
  RT    = 1;
  DN    = 2;
  LT    = 3;
  LO    = 0;
  RH    = 1;
  LH    = 2;
  TT    = 3;
  SQ    = 4;
  SS    = 5;
  ZZ    = 6;
  DRAW  = TRUE;
  ERASE = FALSE;
  GRAPHICS = TRUE;
  SCREENSIZE = 20;
  BACK   =  008;
  TAB    =  009;
  RETURN =  013;
  ENTER  =  013;
  ESC    =  027;
  F1     = -059;
  F2     = -060;
  F3     = -061;
  F4     = -062;
  F5     = -063;
  F6     = -064;
  F7     = -065;
  F8     = -066;
  F9     = -067;
  F10    = -068;
  HOME   = -071;
  UPARR  = -072;
  PAGEUP = -073;
  LTARR  = -075;
  RTARR  = -077;
  ENDKY  = -079;
  DNARR  = -080;
  PAGEDN = -081;
  INSERT = -082;
  DELETE = -083;
  SFTF1  = -084;
  SFTF2  = -085;
  SFTF3  = -086;
  SFTF4  = -087;
  SFTF5  = -088;
  SFTF6  = -089;
  SFTF7  = -090;
  SFTF8  = -091;
  SFTF9  = -092;
  SFTF10 = -093;
  CTLF1  = -094;
  CTLF2  = -095;
  CTLF3  = -096;
  CTLF4  = -097;
  CTLF5  = -098;
  CTLF6  = -099;
  CTLF7  = -100;
  CTLF8  = -101;
  CTLF9  = -102;
  CTLF10 = -103;
  ALTF1  = -104;
  ALTF2  = -105;
  ALTF3  = -106;
  ALTF4  = -107;
  ALTF5  = -108;
  ALTF6  = -109;
  ALTF7  = -110;
  ALTF8  = -111;
  ALTF9  = -112;
  ALTF10 = -113;

implementation

begin
end.